version: "3.3"

services:
  
  regulation-db:
    container_name: regulation-db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: regulations
      MYSQL_USER: regulations
      MYSQL_PASSWORD: regulations
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - regulation-db-data:/var/lib/mysql
    networks: 
      - backnet

  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8090:80
  #   networks:
  #     - backnet

  importdashboard:
    container_name: importdashboard
    build:
      context: importdashboard
      dockerfile: Dockerfile
    ports:
      - 1080:82
    depends_on:
      - regulationdataserver
      - regulationserviceapi
    stdin_open: true

  # importscheduler:
  #   container_name: importscheduler
  #   build:
  #     context: importscheduler
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - regulationdataserver
  #     - regulationserviceapi

  publicdashboard:
    container_name: publicdashboard
    build:
      context: publicdashboard
      dockerfile: Dockerfile
    ports:
      - 1081:81
    depends_on:
      - regulationserviceapi
    stdin_open: true

  regulationserviceapi:
    container_name: regulationserviceapi
    build:
      context: regulationserviceapi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_URL: jdbc:mysql://regulation-db:3306/regulations
      SPRING_DATASOURCE_USERNAME: regulations
      SPRING_DATASOURCE_PASSWORD: regulations
    depends_on:
      - regulation-db
    networks:
      - backnet
  
  regulationdataserver:
    container_name: regulationdataserver
    build:
      context: regulationdataserver
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment: 
      SERVER_PORT: 8081
    
    
      
volumes:
  regulation-db-data:

networks:
  backnet:
